import naverpay from '@naverpay/eslint-config'

export default [
    {
        ignores: [
            // Logs
            'logs',
            '*.log',
            'npm-debug.log*',
            'yarn-debug.log*',
            'yarn-error.log*',

            // Runtime data
            'pids',
            '*.pid',
            '*.seed',
            '*.pid.lock',

            'lib-cov', // Directory for instrumented libs generated by jscoverage/JSCover
            'coverage', // Coverage directory used by tools like istanbul
            '.nyc_output', // nyc test coverage
            '.grunt', // Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
            'bower_components', // Bower dependency directory (https://bower.io/)
            '.lock-wscript', // node-waf configuration
            'build/Release', // Compiled binary addons (https://nodejs.org/api/addons.html)

            // Dependency directories
            'node_modules',
            'jspm_packages',
            'pnpm-lock.yaml',

            '.npm', // Optional npm cache directory
            '.eslintcache', // Optional eslint cache
            '.node_repl_history', // Optional REPL history
            '*.tgz', // Output of 'npm pack'
            '.yarn-integrity', // Yarn Integrity file
            '.env', // dotenv environment variables file

            // next.js build output
            '.next',
            '**/dist',

            'apps/docs/docs',
            '.changeset/*',

            'packages/react-pdf/src/pdfjs-dist/**', // react pdf에 사용될 pdfjs-dist build 파일은 eslint 확인에서 제거합니다.
        ],
    },
    ...naverpay.configs.react,
]
