name: release packages

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.ACTION_TOKEN }}
                  fetch-depth: 0

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: setup pnpm and install dependencies
              uses: pnpm/action-setup@v3
              with:
                  version: 9.1.1
                  run_install: true

            - name: Create Release Pull Request
              id: changesets
              uses: NaverPayDev/changeset-actions/actions/publish@main
              with:
                  github_token: ${{ secrets.ACTION_TOKEN }}
                  git_username: npayfebot
                  git_email: npay.fe.bot@navercorp.com
                  publish_script: pnpm release
                  pr_title: '🚀 version changed packages'
                  commit_message: '📦 bump changed packages version'
                  create_github_release_tag: true
                  formatting_script: pnpm run markdownlint:fix
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
