name: 'size-limit'
on:
    pull_request:
        branches: main

jobs:
    size:
        runs-on: ubuntu-latest
        steps:
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: true
            - uses: actions/checkout@v4
            - uses: andresz1/size-limit-action@v1
              with:
                  build_script: 'build'
                  clean_script: 'clean'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
