name: Analyze Pull Request Size

on:
    pull_request:
        branches:
            - main

jobs:
    size-check:
        runs-on: ubuntu-latest
        steps:
            - uses: pnpm/action-setup@v4
            - name: Run Size Action
              uses: NaverPayDev/size-action@main
              with:
                  cwd: './'
                  github_token: ${{ secrets.ACTION_TOKEN }}
                  build_script: build
