name: 'size-limit'
on:
    pull_request:
        branches: main

jobs:
    size:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'

            - name: setup pnpm and install dependencies
              uses: pnpm/action-setup@v3
              with:
                  version: 9.1.1
                  run_install: true

            - uses: andresz1/size-limit-action@v1
              with:
                  build_script: 'build'
                  clean_script: 'clean'
                  github_token: ${{ secrets.GITHUB_TOKEN }}
